In [ ]:
%a

In [1]:
from befree.model import get_model
from befree.datasets import get_dataset
from befree.optimizers import get_optimizer
from befree.config import get_config
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
config = get_config('befree/config/hesa.yaml')
train, test = get_dataset(config['dataset'])
model = get_model(config['model'])
optim = get_optimizer(model.parameters(), config['optimizer'])

In [2]:
# import torch
# import torch.nn.functional as F
# import numpy as np
# def accuracy (first, second):
#     return sum([1 for i,val in enumerate(first) if first[i] == second[i] ]) / len(first)
# for epoch in  range(100):
#     losses = []
#     accuracyes = []
#     for x,y in train:
#         model_res = lambda: model(x)
#         loss = lambda pred: F.cross_entropy(pred, y)
#         losses.append(optim.step(model_res, loss))
#         accuracyes.append(model(x).tolist(), y.tolist())
#     print("Accuracy ", np.mean(accuracyes))
#     print("Losses ", np.mean(losses))

In [3]:
import torch
def rosenbrock(u, v, noise_range=1):
    noise = torch.rand(1) * noise_range + 1
    return (1-u) ** 2 + 100 * 1 * (v - u ** 2)**2

In [4]:
print("--------- HesaSimple  ---------")
uv = torch.tensor([0.0420, 0.086], requires_grad = True)
optim = get_optimizer([uv], config['optimizer'])
i = 0
loss  = 99999
while loss > 0.0001:
    i+=1
    optim.zero_grad()
    loss = lambda uv: rosenbrock(uv[0], uv[1])
    model_res = lambda: uv
    loss = optim.step(model_res, loss)
    print(f"loss {loss}")
print("Curve iterations:", i)
print("uv = ", uv)
print(f"loss {loss}")

--------- HesaSimple  ---------
Jl before  tensor([-3.3312, 16.8472], grad_fn=<AddBackward0>)
 it |       dist   it/s
001 | 8.7562e+01 607.97
002 | 8.7562e+01 833.28
Terminated in 2 steps (optimal). Took 4.451 ms.
 it |       dist   it/s
001 | 3.4965e+01 738.33
002 | 3.4965e+01 869.94
Terminated in 2 steps (optimal). Took 4.092 ms.
 it |       dist   it/s
001 | 8.9807e-01 814.01
002 | 8.9807e-01 912.49
Terminated in 2 steps (optimal). Took 3.711 ms.
 it |       dist   it/s
001 | 3.5846e-01 884.45
002 | 3.5846e-01 865.93
Terminated in 2 steps (optimal). Took 3.527 ms.
 it |       dist   it/s
001 | 9.1787e-03 879.11
002 | 9.1787e-03 969.47
Terminated in 2 steps (optimal). Took 3.458 ms.
 it |       dist   it/s
001 | 3.5127e-03 994.11
002 | 3.5127e-03 1034.54
Terminated in 2 steps (optimal). Took 3.176 ms.
 it |       dist   it/s
001 | 6.1579e-05 915.17
002 | 6.1579e-05 954.70
Terminated in 2 steps (optimal). Took 3.483 ms.
 it |       dist   it/s
001 | -3.1404e-05 993.90
Terminated in 1 

002 | 3.0946e+01 731.85
Terminated in 2 steps (optimal). Took 4.032 ms.
 it |       dist   it/s
001 | 6.7368e-01 583.75
002 | 6.7368e-01 1058.10
Terminated in 2 steps (optimal). Took 3.861 ms.
 it |       dist   it/s
001 | 2.3235e+00 1021.69
002 | 2.3235e+00 1016.05
Terminated in 2 steps (optimal). Took 3.094 ms.
 it |       dist   it/s
001 | 5.0562e-02 987.91
002 | 5.0562e-02 1073.25
Terminated in 2 steps (optimal). Took 3.107 ms.
 it |       dist   it/s
001 | 1.7444e-01 1047.95
002 | 1.7444e-01 679.43
Terminated in 2 steps (optimal). Took 3.934 ms.
 it |       dist   it/s
001 | 3.7758e-03 931.44
002 | 3.7758e-03 1056.75
Terminated in 2 steps (optimal). Took 3.160 ms.
 it |       dist   it/s
001 | 1.3092e-02 1044.59
002 | 1.3092e-02 1042.71
Terminated in 2 steps (optimal). Took 3.132 ms.
 it |       dist   it/s
001 | 2.6394e-04 993.81
002 | 2.6394e-04 1041.18
Terminated in 2 steps (optimal). Took 3.140 ms.
 it |       dist   it/s
001 | 9.4840e-04 972.93
002 | 9.4840e-04 851.22
Termina

001 | 7.8845e+00 690.34
002 | 7.8845e+00 946.94
Terminated in 2 steps (optimal). Took 4.330 ms.
 it |       dist   it/s
001 | 6.4380e-02 997.18
002 | 6.4380e-02 1047.39
Terminated in 2 steps (optimal). Took 3.110 ms.
 it |       dist   it/s
001 | 1.6590e-02 984.31
002 | 1.6590e-02 1079.09
Terminated in 2 steps (optimal). Took 3.084 ms.
 it |       dist   it/s
001 | 7.5115e-05 1040.11
002 | 7.5115e-05 1081.71
Terminated in 2 steps (optimal). Took 3.051 ms.
 it |       dist   it/s
001 | -5.9830e-05 802.78
Terminated in 1 steps (reached maxiter). Took 1.858 ms.
 it |       dist   it/s
001 | -6.2215e-05 1001.60
Terminated in 1 steps (reached maxiter). Took 1.599 ms.
 it |       dist   it/s
001 | -6.2215e-05 1035.46
Terminated in 1 steps (reached maxiter). Took 1.521 ms.
 it |       dist   it/s
001 | -6.2215e-05 1042.08
Terminated in 1 steps (reached maxiter). Took 1.511 ms.
 it |       dist   it/s
001 | -6.2215e-05 989.29
Terminated in 1 steps (reached maxiter). Took 1.575 ms.
Jl after  te

002 | 3.1095e-04 595.81
Terminated in 2 steps (optimal). Took 4.865 ms.
 it |       dist   it/s
001 | 4.2443e-04 936.43
002 | 4.2443e-04 1038.95
Terminated in 2 steps (optimal). Took 3.257 ms.
 it |       dist   it/s
001 | -2.0933e-05 924.94
Terminated in 1 steps (reached maxiter). Took 1.679 ms.
 it |       dist   it/s
001 | -2.6655e-05 998.35
Terminated in 1 steps (reached maxiter). Took 1.591 ms.
Jl after  tensor([-2.9039, -5.6699], grad_fn=<AddBackward0>)
tensor([0.1601, 0.0067])
loss 1.1170505285263062
Jl before  tensor([-2.3193, -2.0855], grad_fn=<AddBackward0>)
 it |       dist   it/s
001 | 9.8640e+00 827.75
002 | 9.8640e+00 1010.93
Terminated in 2 steps (optimal). Took 3.683 ms.
 it |       dist   it/s
001 | 3.1270e+01 1028.45
002 | 3.1270e+01 1031.72
Terminated in 2 steps (optimal). Took 3.076 ms.
 it |       dist   it/s
001 | 6.6614e-01 607.28
002 | 6.6614e-01 861.49
Terminated in 2 steps (optimal). Took 4.344 ms.
 it |       dist   it/s
001 | 2.1118e+00 878.01
002 | 2.1118e+

In [5]:
print("--------- Newton  ---------")
uv = torch.tensor([-0.25, -0.25], requires_grad = True)
optim = get_optimizer([uv], config['optimizer'])
i = 0
loss  = 99999
while loss > 0.001:
    i+=1
    optim.zero_grad()
    loss = lambda uv: rosenbrock(uv[0], uv[1])
    model_res = lambda: uv
    loss = optim.step(model_res, loss)
print("Newtom iterations:", i)
print("uv = ", uv)

--------- Newton  ---------
Jl before  tensor([-33.7500, -62.5000], grad_fn=<AddBackward0>)
 it |       dist   it/s
001 | 5.5121e+02 1022.76
002 | 5.5121e+02 1064.77
Terminated in 2 steps (optimal). Took 3.081 ms.
 it |       dist   it/s
001 | 2.3256e+02 978.95
002 | 2.3256e+02 923.41
Terminated in 2 steps (optimal). Took 3.554 ms.
 it |       dist   it/s
001 | 8.1066e+00 840.61
002 | 8.1066e+00 1021.70
Terminated in 2 steps (optimal). Took 3.407 ms.
 it |       dist   it/s
001 | 3.4197e+00 896.10
002 | 3.4197e+00 887.50
Terminated in 2 steps (optimal). Took 3.513 ms.
 it |       dist   it/s
001 | 1.1889e-01 996.52
002 | 1.1889e-01 1024.44
Terminated in 2 steps (optimal). Took 3.165 ms.
 it |       dist   it/s
001 | 4.9668e-02 601.15
002 | 4.9668e-02 1031.74
Terminated in 2 steps (optimal). Took 3.941 ms.
 it |       dist   it/s
001 | 1.4134e-03 856.65
002 | 1.4134e-03 733.39
Terminated in 2 steps (optimal). Took 4.191 ms.
 it |       dist   it/s
001 | 2.1563e-04 614.37
002 | 2.1563e-0

 it |       dist   it/s
001 | -5.7953e-05 866.16
Terminated in 1 steps (reached maxiter). Took 1.918 ms.
 it |       dist   it/s
001 | -5.7953e-05 863.46
Terminated in 1 steps (reached maxiter). Took 1.770 ms.
Jl after  tensor([ -5.7953, -19.8549], grad_fn=<AddBackward0>)
tensor([0.0523, 0.0898])
Jl before  tensor([-2.6990, -8.0354], grad_fn=<AddBackward0>)
 it |       dist   it/s
001 | 2.7509e+01 996.46
002 | 2.7509e+01 997.99
Terminated in 2 steps (optimal). Took 3.233 ms.
 it |       dist   it/s
001 | 1.6227e+01 930.68
002 | 1.6227e+01 1011.68
Terminated in 2 steps (optimal). Took 3.247 ms.
 it |       dist   it/s
001 | 2.7195e-01 1031.96
002 | 2.7195e-01 1016.09
Terminated in 2 steps (optimal). Took 3.146 ms.
 it |       dist   it/s
001 | 1.6035e-01 933.50
002 | 1.6035e-01 1048.14
Terminated in 2 steps (optimal). Took 3.242 ms.
 it |       dist   it/s
001 | 2.6617e-03 969.75
002 | 2.6617e-03 1009.85
Terminated in 2 steps (optimal). Took 3.278 ms.
 it |       dist   it/s
001 | 1.495

001 | 2.6854e+06 828.57
002 | 2.6854e+06 909.45
Terminated in 2 steps (optimal). Took 4.167 ms.
 it |       dist   it/s
001 | 1.5029e+04 967.96
002 | 1.5029e+04 1043.27
Terminated in 2 steps (optimal). Took 3.165 ms.
 it |       dist   it/s
001 | 9.1826e+05 1005.05
002 | 9.1826e+05 885.24
Terminated in 2 steps (optimal). Took 3.397 ms.
 it |       dist   it/s
001 | 5.1451e+03 1020.30
002 | 5.1451e+03 1072.77
Terminated in 2 steps (optimal). Took 3.051 ms.
 it |       dist   it/s
001 | 3.1457e+05 1022.68
002 | 3.1457e+05 654.40
Terminated in 2 steps (optimal). Took 3.826 ms.
Jl after  tensor([-246640.6562,  -15055.2383], grad_fn=<AddBackward0>)
tensor([-2.7843, 50.4678])
Jl before  tensor([-576965.8750,  -26284.6289], grad_fn=<AddBackward0>)
 it |       dist   it/s
001 | 6.4313e+05 936.46
002 | 6.4313e+05 1024.43
Terminated in 2 steps (optimal). Took 3.237 ms.
 it |       dist   it/s
001 | 4.2802e+08 971.84
002 | 4.2802e+08 878.87
Terminated in 2 steps (optimal). Took 3.477 ms.
 it |   

In [ ]:
print("--------- SGD  ---------")
uv = torch.tensor([-0.25, -0.25], requires_grad = True)
optimizer = torch.optim.SGD([uv], lr = 0.001)
i = 0
loss = 99999
while loss > 0.0001:
    i+=1
    optimizer.zero_grad()
    loss = rosenbrock(uv[0], uv[1])
    loss.backward()
    optimizer.step()
print("SGD iterations:", i)
print("uv = ", uv)

In [ ]:
print("--------- Adam  ---------")
uv = torch.tensor([-0.25, -0.25], requires_grad = True)
optimizer = torch.optim.Adam([uv], lr = 0.01)
i = 0
loss = 99999
while loss > 0.001:
    i+=1
    optimizer.zero_grad()
    loss = rosenbrock(uv[0], uv[1])
    loss.backward()
    optimizer.step()
print("Adam iterations:", i)
print("uv = ", uv)

In [ ]:
print("--------- Closure  ---------")
uv = torch.tensor([-0.25, -0.25], requires_grad = True)
optimizer = torch.optim.LBFGS([uv], lr = 0.001, history_size=10000)
i = 0
loss = 99999
while loss > 0.001:
    i+=1
    optimizer.zero_grad()
    def closure():
        if torch.is_grad_enabled():
            optimizer.zero_grad()
        loss = rosenbrock(uv[0], uv[1])
        if loss.requires_grad:
            loss.backward()
        return loss
    print(optimizer.step(closure))
print("LBFGS iterations:", i)
print("uv = ", uv)

In [ ]:
print("--------- Adam  ---------")
uv = torch.tensor([-0.25, -0.25], requires_grad = True)
optimizer = torch.optim.Adam([uv], lr = 0.01)
i = 0
loss = 99999
while loss > 0.001:
    i+=1
    optimizer.zero_grad()
    loss = rosenbrock(uv[0], uv[1])
    loss.backward()
    optimizer.step()
print("Adam iterations:", i)
print("uv = ", uv)